export const GET_SUGGESTIONS = 'GET_SUGGESTIONS';
export const SUGGESTIONS_ERROR = 'SUGGESTIONS_ERROR';
export const MOVIES_ERROR = 'MOVIES_ERROR';
export const GET_MOVIES = 'GET_MOVIES';
export const UPDATE_STATUS = 'UPDATE_STATUS';